### ISSUE TITLE
FEATURE REQUEST: Support for same architecture and platform spread as OP CLI

### ISSUE THREAD

**Issue by Riebart** [1Password/connect#10]
The OP CLI is available for a delightful variety of platforms and architectures.

Currently, the binary (and Docker container) for `connect-api` and `connect-sync` are Linux x86-64 only, and the containers don't support multiarch. For many use cases, it would be convenient and useful to run theses on either cloud ARM instances, or in personal environments on Raspberry Pis or similar.

**Comment by verkaufer** [comment]
Hey @Riebart - We're definitely looking into supporting more architectures/platforms (especially as M1 Macs gain larger marketshare). 

We haven't had bandwidth to build and test against a larger architecture set, but we'll provide an update when we can offer those binaries for download.

**Comment by omnisci3nce** [comment]
Any updates? I've been keeping an eye on the Forum post about ARM64 as well. How high on the priority list is this?

**Comment by verkaufer** [comment]
Hey @omnisci3nce - Our team is taking this on now and we hope to provide an update before too long. We'll make an announcement once it's ready.

**Comment by jpcoenen** [comment]
I am glad to announce that we have just released `v1.5.0` of Connect with support for `amd64`, `arm64` and `arm/v7` 🎉
