### ISSUE TITLE
JWT token is invalid base64

### ISSUE THREAD

**Issue by tuxpeople** [1Password/connect#17]
Hi

Not sure if this is the right place, but if not you may be able to point me to the right place.

I try to set up connect in K3S using the official 1Password Helm Chart. My `connect-sync` container is complaining about the auth:

```
{"log_message":"(E) Server: (unable to get credentials and initialize API, retrying in 30s), Wrapped: (failed to FindCredentialsUniqueKey), Wrapped: (failed to loadCredentialsFile), Wrapped: (LoadLocalAuthV2 failed to credentialsDataFromBase64), illegal base64 data at input byte 0","timestamp":"2021-10-22T10:00:01.61311251Z","level":1}
```

This is the part of the values I use for the token in the operator:
```
      token:
        name: onepassword-token
        key: token
```

I created the appropriate secret like this:

```
kubectl -n kube-system create secret generic onepassword-token --from-literal=token=<TOKEN>
```

I created the token and the `1password-credentials.json` on the 1Password website. I think the token I got is wrong. I tried to decode it:

```
echo "<TOKEN>" | base64 -d
Illegal character '.' in input file.
{"alg":"ES256","kid":"avcxxxxxxxxxxxxxxxxxxxxa","typ":"JWT
```

The token I got from the website has two dots (`.`) in it, which is not valid base64. I tried it without the dots, but this doesn't work either. I also created new token, same problem.

**Comment by florisvdg** [comment]
What are you passing to the Connect sync container? Is that the token or the `1password-credentials.json` file?

And the Connect token is supposed to have 2 dots in it, so that's fine.

**Comment by verkaufer** [comment]
Hey @tuxpeople Did you get this resolved?

**Comment by tuxpeople** [comment]
Yes, I have. I started again from scratch, then it worked. As some time has been gone between the two attempts, I can't tell exactly I did change except from that the second time, I used the cli to get the jwt. I assume the error layed somwhere in how I created the secret containing the json. However, It worked and I was able to test the secrets automation to check if it fits my usecase.

**Comment by ndegory** [comment]
I had the same issue.

```
{"log_message":"(E) Server: (unable to get credentials and initialize API, retrying in 30s), Wrapped: (failed to FindCredentialsUniqueKey), Wrapped: (failed to loadCredentialsFile), Wrapped: (LoadLocalAuthV2 failed to credentialsDataFromBase64), illegal base64 data at input byte 0","
timestamp":"2022-08-29T23:34:22.541943876Z","level":1}
```
This was because I used the 1password-credentials.json as text without base64 encoding in the Kubernetes secret. In other words, it's base64 encoded **twice**

```
➜ k get secrets -n 1password op-credentials -o yaml | yq e '.data.op-session' | base64 --decode | base64 --decode
{"verifier":{"salt":"REDACTED","localHash":"REDACTED"},"encCredentials":{"kid":"localauthv2keykid","enc":"A256GCM","cty":"b5+jwk+json","iv":"REDACTED","data":"REDACTED"},"version":"2","deviceUuid":"REDACTED","uniqueKey":{"alg":"A256GCM","ext":true,"k":"REDACTED","key_ops":["encrypt","decrypt"],"kty":"oct","kid":"REDACTED"}}
```

**Comment by antham** [comment]
In my case it was the same than with @ndegory but I got this after encoding the secret twice in base64  `Server: (LoadLocalAuthV2 failed to credentialsDataFromBase64), illegal base64 data at input byte 1474` because I did not use the `-w 0` on `base64` to remove the new line
