### ISSUE TITLE
/files is not supported in connect-api:1.2.0

### ISSUE THREAD

**Issue by nml11c** [1Password/connect#19]
### Current behavior
- Item have files in it
- `{{baseUrl}}/vaults/:vaultUuid/items/:itemUuid/files` returns `404` and no logs on `connect-api` side
- `{{baseUrl}}/vaults/:vaultUuid/items/:itemUuid` with the same ids works just fine and log it

### Expected behavior
 `{{baseUrl}}/vaults/:vaultUuid/items/:itemUuid/files` returns a list of files in an item.

### Context
Image: `connect-api:1.2.0`

**Comment by verkaufer** [comment]
Hey @nml11c - You'll need to update to the [v1.3.0 tag](https://github.com/1Password/connect/blob/main/CHANGELOG.md#v130) for the API and Sync containers before you can start using the `/files` endpoint. 

File support is not available before v1.3.0. You can review the updated [OpenAPI spec](https://github.com/1Password/connect/blob/main/docs/openapi/spec.yaml) for more details about the `/vaults/:uuid/items/:itemUuid/files` endpoint here: https://github.com/1Password/connect/blob/9e454a26d51c2a82b7df12be98ef3b3b281aff24/docs/openapi/spec.yaml#L937
