### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by mafrosis** [1Password/connect#33]
Says it's docs - but docs for where?

I don't see the content on: https://developer.1password.com/docs/connect

Should issues for Connect go on here? Or somewhere else?

**Comment by codertyler** [comment]
Hey @mafrosis, this repo is maintained for the following purposes:

- Raising Connect related issues.
- Providing examples for deploying Connect in different environments. 

As we move forward we are making the docs portal which you mentioned in your comment as our sole source of truth for documentations. Therefore, we are working on resolving the discrepancies between the two. 

Could you tell me which specific content were you looking for?

Thank you!
