### ISSUE TITLE
Incorrect spec for Item: File

### ISSUE THREAD

**Issue by jonas-zipprick** [1Password/connect#43]
Spec says that `Item: File` contains a property called `content_path`.
Instead the property returned is capitalized as `contentPath` when requesting from the current live API.

**Comment by codertyler** [comment]
Hi @jonas-zipprick! We had the issue few weeks ago and it should've been fixed. Which SDK are you using?

**Comment by jonas-zipprick** [comment]
For the gateway we are using docker images `1password/connect-api:1.5.4` and `1password/connect-sync:1.5.4`.
We do API requests using node `cross-fetch: 3.1.5`

**Comment by codertyler** [comment]
Hey @jonas-zipprick sorry for following up so late, I believe this has been resolved, has it been resolved on your end?

**Comment by dustin-ruetz-1p** [comment]
Hi @jonas-zipprick - I'm going to close this issue now, but feel to re-open/comment if you need anything else. Thanks!
