### ISSUE TITLE
/items filtering restrictions (category)

### ISSUE THREAD

**Issue by mmesdag** [1Password/connect#53]
When filtering on the item list [endpoint](https://developer.1password.com/docs/connect/connect-api-reference#list-items) is the only filterable field 'title'? I'd like to filter by 'category' but that returns `Unsupported request filter`. Curious if this is a bug, or if the filtering is limited to a subset of fields on the item, and if so if that's documented anywhere

**Comment by ag-adampike** [comment]
Hey @mmesdag! Thanks for filing this issue.

Currently, we support the following filtering schemes (this is exhaustive):

- vaults (`/v1/vaults`) by `name`, and
- items (`/v1/vaults/{vaultUUID}/items`) by `title` or `tag`

I'll ask our docs team to take a look and clarify this accordingly. Thanks for bringing it to our attention!
