### ISSUE TITLE
no example for 1password-credentials.json found

### ISSUE THREAD

**Issue by ogaida** [1Password/connect#67]
I do not know how the file `1password-credentials.json` should look like. Could someone please provide an example. that would be really pleasant. thanks in advance !

**Comment by jillianwilson** [comment]
Hi there, the contents of your 1password-credentials.json will look something like this:

```{"verifier":{"salt":"LXTNtdiGiX4qubks1-M1Uw","localHash":"cLmz2Nu8sJVSUt__I6HpJYGz5VcKJ8YqTDGezPre1fo"},"encCredentials":{"kid":"localauthv2keykid","enc":"A256GCM","cty":"b5+jwk+json","iv":"otZagi8vomLpGB2L","data":"mDthYuIf3Ozr2p2UgJKHiFgyN9d3nkrN-QhZA6htUCmYBCY4-r4dy04m3VW5kxUjeq3H7X12WAjSBL07d5lpBFyzlShe89uqTbAkIhQCXEQqEdtDqW02elSggwRU4nHPn_UzvGdZHZ8Oxrz6hReJ8NXDyZyFhOPreXrleC7N5OfxEgu3iP-EIS5X1mja1ehjfKyuUF3kKvIq41MbG_xyHtJDhRZwt51EMTDHQs0iA3Dykl0Tp8bVswlLMpWBszsYbGGVsOOKGPrwNk-YrhiyHhX3eJ4AgQ7NMpIzEOMOOdRRMqrxtV3G05lp6j9UMAlseSlpdvFLHIjJM5LfzG6hRS8y8Ukzzp9EBVXwK9zewQvuIOncg30s9ISVgXL4C2FC7mW9-cBmCILnU9-4R_No3KIZsOuVK98XEV117Np8TaBIMgZ7P9EVkXgXNxUnPrFq0Xg7WzPyLco1gdsMxTZnDhkhiDeSCaXI-gKjtbJhW4dSS9x7QgVUHnVts7BMGzLHpSV4e0-Qxq9dZ99ef0V-C2tGnn9vIhgrhFQIRbR6oKUwfZjpGWkVsPi5jg8PLsb7whgzWtFq98G53nRUX85-fX_49AB4XiW55Xm85M8FlKxAQK-xcoChRkazUqFmGGbWHXze9pZ9-Ds2VsDIwZbWoeBTeys"},"version":"2","deviceUuid":"rl5xahcbuydfyy2za2rgie6tdy","uniqueKey":{"alg":"A256GCM","ext":true,"k":"84eqZDcnB0qfOjuqRnyzOPJFiwy-u1TVobyJuM0evho","key_ops":["encrypt","decrypt"],"kty":"oct","kid":"zxqj74zyl6at5tt37t3xvoafum"}}```
